baseURL: "https://yug95.github.io/"
title: "Yogesh Agrawal"
theme: "PaperMod"
languageCode: "en-us"
params:
  author: "Yogesh Agrawal"
  defaultTheme: "auto"
  ShowReadingTime: true
  ShowCodeCopyButtons: true

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
